// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/bodice": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/bodice" | "/*";
  };
  "./presentation/pages/bodice.tsx": {
    id: "presentation/pages/bodice";
    page: "/bodice";
  };
  "./presentation/pages/404.tsx": {
    id: "presentation/pages/404";
    page: "/" | "/*";
  };
};

type RouteModules = {
  "root": typeof import("./src/root.tsx");
  "presentation/pages/bodice": typeof import("./src/./presentation/pages/bodice.tsx");
  "presentation/pages/404": typeof import("./src/./presentation/pages/404.tsx");
};